print("Smarika Pokhrel Portfolio")
print("--------------------------")
print("Website files are ready.")
print()
print("To publish the website:")
print("1. Commit your changes to GitHub.")
print("2. Enable GitHub Pages.")
print("3. Open your custom domain.")
